import { useEffect, useMemo, useState } from 'react';
import { Link, useParams } from 'react-router-dom';
import { ArrowLeft, ArrowRight, ArrowUp, Swords, Pause, Play as PlayIcon, Heart, Coins, RotateCcw, Flag } from 'lucide-react';
import PhaserGame from '../components/PhaserGame';
import { createBridge } from '../game/bridge';
import { levels } from '../game/data/levels';
import { useProgress } from '../app/ProgressContext';
function Control({ action, label, bridge, children }) {
  const release = () => bridge.emit('input', { action, down: false });
  return <button className="touch-button" aria-label={label} title={label} onContextMenu={e => e.preventDefault()} onPointerDown={e => { e.preventDefault(); e.currentTarget.setPointerCapture(e.pointerId); bridge.emit('input', { action, down: true }); }} onPointerUp={release} onPointerCancel={release} onLostPointerCapture={release}>{children}</button>;
}
export default function Play() {
  const { levelId } = useParams(); const level = levels[levelId]; const { save, complete } = useProgress();
  const bridge = useMemo(createBridge, []); const [hud, setHud] = useState({ health: 3, coins: 0 }); const [paused, setPaused] = useState(false); const [result, setResult] = useState(null);
  useEffect(() => { const off = [bridge.on('hud', setHud), bridge.on('paused', setPaused), bridge.on('result', data => { setResult(data); if (data.won) complete(data.coins); })]; return () => off.forEach(fn => fn()); }, [bridge, complete]);
  function restart() { setResult(null); setPaused(false); bridge.emit('restart'); }
  if (!level) return <main className="loading">This path is still undiscovered.<Link to="/worlds">Return to the map</Link></main>;
  return <main className="play-screen"><header className="play-header"><Link to="/worlds/meadow/levels" className="icon-button" title="Leave level" aria-label="Leave level"><ArrowLeft /></Link><div><span className="eyebrow">MEADOW LANDS / 1-1</span><h1>{level.name}</h1></div><span className="play-chapter">AARANYA CHRONICLES</span></header><div className="game-stage"><PhaserGame bridge={bridge} level={level} settings={save.settings} /><div className="game-hud"><span className="hearts" aria-label={`${hud.health} hearts`}>{[1, 2, 3].map(n => <Heart key={n} size={23} fill={n <= hud.health ? '#df716a' : 'transparent'} color={n <= hud.health ? '#df716a' : '#9aa79c'} />)}</span><span className="coin-count"><Coins size={20} /> {hud.coins} / 8</span><button className="icon-button" aria-label="Pause" title="Pause" onClick={() => bridge.emit('pause', true)}><Pause size={21} /></button></div><div className="touch-controls"><div><Control bridge={bridge} action="left" label="Move left"><ArrowLeft /></Control><Control bridge={bridge} action="right" label="Move right"><ArrowRight /></Control></div><div><Control bridge={bridge} action="attack" label="Attack"><Swords /></Control><Control bridge={bridge} action="jump" label="Jump"><ArrowUp /></Control></div></div>{(paused || result) && <div className="game-overlay"><section className="dialog" role="dialog" aria-modal="true" aria-labelledby="dialog-title"><Flag className="dialog-icon" size={32} /><p className="eyebrow">{result?.won ? 'CHAPTER COMPLETE' : result ? 'A LITTLE COURAGE' : 'TAKE A BREATH'}</p><h2 id="dialog-title">{result?.won ? 'The first light is yours.' : result ? 'Every journey takes practice.' : 'The forest can wait.'}</h2>{result && <p>{result.won ? `${result.coins} of 8 coins collected. Your progress is saved.` : 'Try the path again.'}</p>}{!result && <button className="primary-button" onClick={() => bridge.emit('pause', false)}><PlayIcon size={18} />Resume journey</button>}<button className="secondary-button" onClick={restart}><RotateCcw size={18} />{result ? 'Play again' : 'Restart level'}</button><Link className="text-link" to="/worlds/meadow/levels">Back to levels <ArrowRight size={16} /></Link></section></div>}</div><footer className="game-footer"><span>01 <span className="muted">/</span> THE FIRST STEPS</span><span><Flag size={14} /> The sanctuary awaits</span></footer></main>;
}
